fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("Compiling proto files...");

    tonic_prost_build::configure()
        // .out_dir(std::path::Path::new("src/generated").as_ref())
        .out_dir("src/generated")
        // .type_attribute(".", "#[derive(serde::Serialize)]")
        .build_server(true)
        .build_client(false)
        // .file_descriptor_set_path(std::path::Path::new("src/generated/biconom_file_descriptor.bin").as_ref())
        .file_descriptor_set_path("src/generated/biconom_file_descriptor.bin")
        .compile_protos(&[
                "biconom/types/account.proto",
                "biconom/types/asset.proto",
                "biconom/types/account_policy.proto",
                "biconom/types/bonus.proto",
                "biconom/types/bonus_policy.proto",
                "biconom/types/boundary.proto",
                "biconom/types/calculation.proto",
                "biconom/types/community.proto",
                "biconom/types/community_policy.proto",
                "biconom/types/confirmation.proto",
                "biconom/types/confirmation_policy.proto",
                "biconom/types/currency.proto",
                "biconom/types/currency_policy.proto",
                "biconom/types/currency_pair.proto",
                "biconom/types/currency_pair_policy.proto",
                "biconom/types/distributor.proto",
                "biconom/types/distributor_policy.proto",
                "biconom/types/distributor_branch.proto",
                "biconom/types/distributor_branch_policy.proto",
                "biconom/types/google_authenticator.proto",
                "biconom/types/google_authenticator_policy.proto",
                "biconom/types/locale.proto",
                "biconom/types/mnemonic.proto",
                "biconom/types/network.proto",
                "biconom/types/network_policy.proto",
                "biconom/types/network_account.proto",
                "biconom/types/network_account_policy.proto",
                "biconom/types/network_partition.proto",
                "biconom/types/network_partition_policy.proto",
                "biconom/types/password_policy.proto",
                "biconom/types/payment_destination.proto",
                "biconom/types/payment_destination_registry.proto",
                "biconom/types/payment_network.proto",
                "biconom/types/payment_network_currency.proto",
                "biconom/types/payment_network_operation_settings.proto",
                "biconom/types/payment_operation_settings.proto",
                "biconom/types/presence.proto",
                "biconom/types/invite_link.proto",
                "biconom/types/invite_link_policy.proto",
                "biconom/types/ledger.proto",
                "biconom/types/ledger_policy.proto",
                "biconom/types/ledger_transaction.proto",
                "biconom/types/relationship.proto",
                "biconom/types/rounding.proto",
                "biconom/types/session.proto",
                "biconom/types/session_policy.proto",
                "biconom/types/slot.proto",
                "biconom/types/slot_policy.proto",
                "biconom/types/slot_branch.proto",
                "biconom/types/slot_branch_policy.proto",
                "biconom/types/sort.proto",
                "biconom/types/subject.proto",
                "biconom/types/trace.proto",
                "biconom/types/tree.proto",
                "biconom/types/tree_policy.proto",
                "biconom/types/tree_distributor.proto",
                "biconom/types/tree_distributor_policy.proto",
                "biconom/types/tree_partition.proto",
                "biconom/types/tree_partition_policy.proto",
                "biconom/types/user.proto",
                "biconom/types/user_policy.proto",
                "biconom/types/wallet_operation.proto",
                "biconom/types/wallet_type.proto",
                "biconom/types/wallet_type_currency.proto",
                "biconom/types/wallet_balance.proto",
                "biconom/types/wallet.proto",

                "biconom/client/account/account.proto",
                "biconom/client/auth/auth.proto",
                "biconom/client/confirmation/confirmation.proto",
                "biconom/client/currency/currency.proto",
                "biconom/client/currency_pair/currency_pair.proto",
                "biconom/client/distributor/distributor.proto",
                "biconom/client/google_authenticator/google_authenticator.proto",
                "biconom/client/invite_link/invite_link.proto",
                "biconom/client/locale/locale.proto",
                "biconom/client/mnemonic/mnemonic.proto",
                "biconom/client/password_policy/password_policy.proto",
                // "biconom/client/payment_destination/payment_destination.proto",
                "biconom/client/payment_network/payment_network.proto",
                "biconom/client/payment_network_currency/payment_network_currency.proto",
                "biconom/client/session/session.proto",
                "biconom/client/wallet_type/wallet_type.proto",
                "biconom/client/wallet_type_currency/wallet_type_currency.proto",
        ], &["proto"])
        .unwrap_or_else(|e| panic!("Failed to compile protos: {:?}", e));

    println!("Proto files compiled successfully.");
    Ok(())
}
